### ISSUE TITLE
Betaflight vtx patches

### ISSUE THREAD

**Issue by FNGflaitz** [emuflight/EmuConfigurator#12]
When you turn expert mode to always on, the betaflight vtx patches show up under release and release candidates

**Comment by AndreySemjonov** [comment]
This should be fixed in latest 0.1.2 configurator. Can you check please ?

**Comment by FNGflaitz** [comment]
If it hasn't been updated as of 10:00 9/21/19 it's still there.

**Comment by Quick-Flash** [comment]
This is now fixed closing this.
