### ISSUE TITLE
Configurator 0.3.2 doesn't start and remains minimized on Win10

### ISSUE THREAD

**Issue by Vanalio** [emuflight/EmuConfigurator#210]
Configurator 0.3.2 doesn't start since yesterday. I double click it and it remains on the bar, minimized. I tried to remove and reinstall it, issue still exists.

**Comment by Vanalio** [comment]
I managed to maximise the application using alt-space shortcut. Might be windows bug.

**Comment by nerdCopter** [comment]
thank you.
