### ISSUE TITLE
deb file does not install, Linux

### ISSUE THREAD

**Issue by JoelHallklint** [emuflight/EmuConfigurator#218]
Hi, i could not install the .deb file ??
Something wrong with it?

MXLinux 19.2

/J

**Comment by nerdCopter** [comment]
i have use every `.deb` without issue on Debian 10 and Ubuntu 19.04
`sudo dpkg -i emuflight-configurator_0.3.2_amd64.deb`
please paste the output of your install attempt, thank you.

**Comment by JoelHallklint** [comment]
Thank you, it works.
I tried to use Gdebi as usual...
