### ISSUE TITLE
Hangups switching from "PID Tuning Tab"

### ISSUE THREAD

**Issue by N4V1G4T0R** [emuflight/EmuConfigurator#22]
I experience occasional hangups of the configurator when switching from the "PID Tuning Tab" to another tab. The configurator just keeps showing the PID Tuning Tab. I could not figure out the pattern of the hangup. It just sometimes occurs for no real reason.

Workaround: disconnect and reconnect.

**Comment by gretel** [comment]
@N4V1G4T0R i'm also experience this type of bug, but the author can not reproduce it. i am sorry.

**Comment by valeratlt80** [comment]
У меня в режиме настроек через OSD коптер тоже зависает иногда причем намертво даже не переключает полётные режимы тумблерами  помогает только жесткий перезапуск

**Comment by loutwice** [comment]
this one is working now

**Comment by nerdCopter** [comment]
i get this too, still. i think it's a firmware issue.

**Comment by gretel** [comment]
ya me too.

**Comment by gretel** [comment]
@emuflight/emuteam i am still getting this. it is annoying. please stop implementing new features but squish these ancient bugs instead. may be less fun but it is more important.

**Comment by nerdCopter** [comment]
* specific issue source found: if `*.json` files do not exist, gui will crash (`pid_tuning.js`), but not exit.
* logical solution would be check for file existing before attempting to populate drop-down.
