### ISSUE TITLE
Anti Gravity - No Bubble Help Popup Description

### ISSUE THREAD

**Issue by Mystery-D** [emuflight/EmuConfigurator#23]
Just noticed there is no description in the '?' help bubble popup for the description for Anti Gravity (in PID tuning)

**Comment by loutwice** [comment]
thank you- will correct this

adding pidTuningAntiGravityHelp in each langages  file (already done FR/En)

**Comment by gretel** [comment]
@loutwice https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
