### ISSUE TITLE
Two Serial Rx

### ISSUE THREAD

**Issue by N4V1G4T0R** [emuflight/EmuConfigurator#24]
Minor Bug

The Configurator allows using two UARTs for Serial Rx.

The RX (TBS Crossfire Nano) is on UART 1. Default Settings for the FC (I tried the HolyBro Kakute F7 this time) is UART 6. So, I activated Serial RX for UART 1 and deactivated it for UART 6, hit save. After a reboot I saw Serial Rx activated for both UARTs, 1 and 6. Which might be a conflicting setting and should be rejected.

Well, I tried flying with it, and it did. 

# serial
serial 0 64 115200 57600 0 115200
serial 6 1024 115200 57600 0 115200

**Comment by gretel** [comment]
its okayish if it flies :) thanks for the report
