### ISSUE TITLE
Export gyro data to GoPro GPMF file for reelsteady

### ISSUE THREAD

**Issue by jacobbloy** [emuflight/EmuConfigurator#26]
Export gyro data to GoPro GPMF file for reelsteady, this would allow us to use our turtle or runcam split camera or DJI FPV system HD recording and input them into the reelsteady go software and get supper smooth camera footage with out the need for a GoPro. Reelsteady said the emu flight guys are looking into making a tool.

**Comment by gretel** [comment]
thanks @jacobbloy please joins us at https://discord.gg/nP9Hhs we are working on this

**Comment by jbstand** [comment]
Hey guys,

I'm really interested in this feature, if I can be of any help let me know!

**Comment by gretel** [comment]
@jbstand we are accepting pull requests, thank you.
