### ISSUE TITLE
Problem EmuFlight Configurator.

### ISSUE THREAD

**Issue by pbiopy** [emuflight/EmuConfigurator#29]
Hello,
Does not work with Macos X Catalina the latestversion. **The Emuflight configurator does not run**.
Thank You very much for your help.

**Comment by djerfy** [comment]
Hello @pbiopy, I don't have error with the latest version of Catalina (10.15.2).
What is your problem?

**Comment by pbiopy** [comment]
Thank you for your help but it's resolved.
