### ISSUE TITLE
[Firmware Request] T-Motor F7 HD

### ISSUE THREAD

**Issue by spawn94260** [emuflight/EmuConfigurator#291]
Hi everyone,

Can you add T-motor F7 Hd firmware on Emuflight ? Or can i upload "Tmotor F7" target for testing before ?

Thanks for your help and your works 👍

**Comment by nerdCopter** [comment]
@spawn94260 , do you have code to PR, or just asking for it to be created?
if Kaiowarez has to create the target, then please send a cli `dump` from betaflight and website link to product/specifications.

**Comment by nerdCopter** [comment]
moving to : https://github.com/emuflight/EmuFlight/issues/421

**Comment by nerdCopter** [comment]
@spawn94260 `uses the same TMOTORF7 target`
