### ISSUE TITLE
[feature request] sharkbyte support

### ISSUE THREAD

**Issue by hankhill303** [emuflight/EmuConfigurator#418]
is there any hope or any word at all on emuflight using sharkbyte? I would love to switch all of my quads to emu but my favorites I run with the sharkbyte system and I would love love love to see support for that. thank you! cheers.

**Comment by nerdCopter** [comment]
there is some test versions of HDZero/Sharkbyte available via EmuFlight Discord: https://discord.gg/BWqgBg3
ref #449 
ref https://github.com/emuflight/EmuFlight/pull/775
