### ISSUE TITLE
PID Tab is Blank.

### ISSUE THREAD

**Issue by NeilGaede** [emuflight/EmuConfigurator#49]
Everything else works, including CLI that shows all the tasks are running, but when I click on the PID tab everything is blank, not just zeros, but blank. I can toggle values and change them, but there is nothing in the boxes under presets or anything.

**Comment by NeilGaede** [comment]
Configurator 0.2.12 win64.

**Comment by NeilGaede** [comment]
Tried configurator 2.11 and same problem.

**Comment by NeilGaede** [comment]
Configuration version 2.0 works fine.

**Comment by nerdCopter** [comment]
this happens on occasion. reboot/reinstall configurator, but also see 
https://github.com/emuflight/EmuFlight/issues/67#issuecomment-590365556
i.e. uninstall old versions & delete installation folder before installing new versions.

**Comment by Canaill51** [comment]
I did have experienced same issue when was offline. When connecting to any Internet connection, issue was fixed. I am wondering if there is not a relation between presets updates and this concern? As presets are impacting PID and Filters... @nerdCopter ?

**Comment by mdibe** [comment]
I can confirm the same issue happens to me when offline. Usually outside when flying at the field.
As soon as I get home and connect to the wifi the issue is solved.

**Comment by nerdCopter** [comment]
now everything makes sense, thank you very much.  it's looking for the presets, which are online. 
one of us will look into a solution.

**Comment by gretel** [comment]
@emuflight/emuteam there should be timeouts and error handling in place for all non-local transactions like http requests.

**Comment by Mr-Buff** [comment]
Me too.. 
On the PID-config everything is blank..and after get in to PID-config GUI get stuck...
try to connect internet but doesn't work.
reinstall is work again in first connect and after that blank again.
use on Mac OS 10.14 Mojave.

**Comment by AndreySemjonov** [comment]
What GUI version ?

**Comment by gretel** [comment]
it's because the threads hang when there is no internet connection, or firewall blocking the requests. code needs to timeout and fail properly.

**Comment by AndreySemjonov** [comment]
Its working for when no internet connection. Maybe it hang when there is connection, but can't download (or connection slow).

**Comment by gretel** [comment]
it does not maybe hang but for sure.

**Comment by AndreySemjonov** [comment]
I not talking about does it hang or not :) I try to replicate this issue and I can't. If I turn off internet connection it is working for me.

**Comment by gretel** [comment]
the reporter mentioned a different operating system. you gonna say "i have windows only" now and keep this going on forever :)

**Comment by AndreySemjonov** [comment]
Please look 1st report it tells about windows. To fix something I need to replicate it to check does it help or not. If you know how you can tell.

**Comment by gretel** [comment]
cause i read the code you published. sorry for disturbance. i'm kinda like off here.

**Comment by AndreySemjonov** [comment]
Your comment was really helpful thanks
