### ISSUE TITLE
Mac OSX Configurator Not Compatible with OSX Catalina

### ISSUE THREAD

**Issue by andimon1** [emuflight/EmuConfigurator#51]
Note that the OSX Configurator does not work with OSX Catalina. I'm not sure on this, but I believe this version of the OS does not allow for 32 bit programs to run. The OSX fork would have to be written in 64 bit. If you have any insight on this, I'd appreciate it. I'm stuck with Betaflight until this is resolved one way or another.

**Comment by gretel** [comment]
builds are 64bit and working fine on cataline. please provide further information.
