### ISSUE TITLE
Mac OSX firmware flashing fail

### ISSUE THREAD

**Issue by mdibe** [emuflight/EmuConfigurator#65]
Flashing a firmware on Mac OS seems to only work on 0.2.0 and previous.
All versions released after (0.2.11, 0.2.12, 0.2.12-RC2) are not able to flash the firmware:
The flight controller goes into DFU mode but then nothing happens.
0.2.0 seems to work fine even flashing the latest firmware.

**Comment by mdibe** [comment]
Digging a little bit more it seems like the issue comes from the nwjs file.
0.2.0 uses 0.36.2-sdk which works fine.
0.2.11-12 use 0.42.2-sdk which is causing the issue.
I have found that the issue begins with version 0.37.1-sdk. So in the meantime I'm using configurator 0.2.13 with 0.37.0-sdk and seems to work fine.
I hope this could help to fix the problem.

**Comment by gretel** [comment]
@mdibe thanks for the report! i have been flashing lots using the recent releases which have been build using `0.42.2` so i'm bit confused.

**Comment by mdibe** [comment]
@gretel thanks. It might be that my MacOS High Sierra is too outdated somehow.

**Comment by gretel** [comment]
@mdibe think same. sorry we can not support older versions of macos at the moment.
besides, it's possible to compile the configurator from source code, and change the definition accordingly at https://github.com/emuflight/EmuConfigurator/blob/a2c45a3c50b8825ec2c6aac6809053baf9596047/gulpfile.js#L43
you need `node10` and `yarn` installed:
```
yarn install
yarn gulp apps --osx64
```
